dependencies:
- name: jxboot-resources
  repository: https://jenkins-x-charts.github.io/v2/
- alias: tekton
  name: tekton
  repository: https://jenkins-x-charts.github.io/v2/
- alias: prow
  condition: prow.enabled
  name: prow
  repository: https://jenkins-x-charts.github.io/v2/
- alias: lighthouse
  condition: lighthouse.enabled
  name: lighthouse
  repository: https://jenkins-x-charts.github.io/v2/
- alias: lighthouse-jx
  condition: lighthouse.enabled
  name: lighthouse-jx
  repository: https://jenkins-x-charts.github.io/v2/
- alias: bucketrepo
  condition: bucketrepo.enabled
  name: bucketrepo
  repository: https://jenkins-x-charts.github.io/v2/
- name: jenkins-x-platform
  repository: https://jenkins-x-charts.github.io/v2/
#- condition: chartmuseum.enabled
#  name: chartmuseum
#  repository: https://jenkins-x-charts.github.io/v2/
